// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhIkCuW0k538m2Z6i8Sp8snbTn8tFQvY',
    appId: '1:1017033945544:web:f66111ea668dbc62ced0fd',
    messagingSenderId: '1017033945544',
    projectId: 'myinstar-e29d7',
    authDomain: 'myinstar-e29d7.firebaseapp.com',
    storageBucket: 'myinstar-e29d7.appspot.com',
    measurementId: 'G-FGQXLE57SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hrpxT-24P3OF8z8VI1agwuJw4uITAks',
    appId: '1:1017033945544:android:1ce3dc1455e83aaaced0fd',
    messagingSenderId: '1017033945544',
    projectId: 'myinstar-e29d7',
    storageBucket: 'myinstar-e29d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQelUi7An9Q2quvV-s17t8M4Ao3ceA9g',
    appId: '1:1017033945544:ios:3a23e5ee09bbfafeced0fd',
    messagingSenderId: '1017033945544',
    projectId: 'myinstar-e29d7',
    storageBucket: 'myinstar-e29d7.appspot.com',
    iosClientId: '1017033945544-gmbdio70i01761bau13a2jm6s6h5mi89.apps.googleusercontent.com',
    iosBundleId: 'com.coderlee.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQelUi7An9Q2quvV-s17t8M4Ao3ceA9g',
    appId: '1:1017033945544:ios:3a23e5ee09bbfafeced0fd',
    messagingSenderId: '1017033945544',
    projectId: 'myinstar-e29d7',
    storageBucket: 'myinstar-e29d7.appspot.com',
    iosClientId: '1017033945544-gmbdio70i01761bau13a2jm6s6h5mi89.apps.googleusercontent.com',
    iosBundleId: 'com.coderlee.instagram',
  );
}
